### ISSUE TITLE
lack of documentation

### ISSUE THREAD

**Issue by mimoo** [mirage/digestif#139]
just a general comment, but I'm trying to understand some code making use of this library and there's code like

```
  let h = Digestif.blake2s 32 in
```

and there doesn't seem to be any official documentation anywhere I can find on what 32 is here. 

(The doc is here: https://ocaml.org/p/digestif/0.9.0/doc/Digestif/index.html#val-blake2s but there is no actual documentation)

**Comment by dinosaure** [comment]
I try to figure out how to complete the documentation but since #103, I arbitrary did the choice to delete this argument (which can be error-prone and generate segfaults with the C backend). This change was done 2 years ago (August 2020) and you are probably stuck on a old version of `digestif` (`0.9.0`).

If you need to generate a `BLAKE2{B,S}` with a specific size, I can re-introduce something which can help you to do so. In that case, please fill a new issue. I can close this issue which is not related to the _upstream_ version of `digestif`. Thanks for your patience.
