### ISSUE TITLE
BLAKE2: HMAC functions implement keyed MAC

### ISSUE THREAD

**Issue by emillon** [mirage/digestif#46]
Hi,

For BLAKE2, the `hmac_*` functions do not actually implement HMAC.

More precisely, HMAC is a way to turn any hash function into a MAC. But some hash functions also have a keyed variant which is another MAC function.

Here, `Digestif.BLAKE2S.hmac_string` implements keyed BLAKE2s, not HMAC-BLAKE2s as expected.

I'm happy to provide a patch, but this will break compatibility obviously.

Let me know what you think.

**Comment by emillon** [comment]
(basically this is the same bug as pyca/cryptography#3869)

**Comment by dinosaure** [comment]
Indeed you are right and I was disturbed for a long time by a misinterpretation between what `cryptography` did (python package) and RFC2104 explained (and why HMAC of `BLAKE2*` differs from what I did about `SHA*`).

It's mostly because I tested my implementation with `cryptography` than I implemented like this. I will happy to let you to fix this problem and it will clean a little bit a weird part of `digestif` (an `hashtbl` which contain application of `functors` ...).

**Comment by emillon** [comment]
Sure! Shall I remove completely the keyed version, or just expose it under a different API?

**Comment by dinosaure** [comment]
Under a different API is a good solution I believe.

**Comment by emillon** [comment]
After thinking a bit about this, I believe that the simplest thing to do is to just remove the custom keyed version.

The nice part about `digestif` is how regular it is, exposing the same interface for all hash functions. Apart from HMAC, different hash functions will have different MAC constructions, but they'll have different security properties, so it seems unwise to expose them under the same API.

I could see a use case for a lower-level API where you'd call `blake2b` directly, but it seems premature to expose it in `digestif`'s public API.

**Comment by dinosaure** [comment]
Good point, feel free to re-regularize the API 👍 Then, about compatibility break, I think @vbmithr shoud be interesting about that I think.
